GET http://localhost:3000/api/users/123123


###
GET http://localhost:3000/api/about


###
GET http://128.140.125.244:5000/api/report
Content-Type: application/json

{
    "id":123123,
    "year":2028,
    "month":1
}